Make modules in other/ directory importable
slarse/Python pull request #24
Opened 2019-02-22 10:58 UTC by larshum

#21

2019-02-22 12:45 UTC, mnil2 requested changes
Good, but for one problem. Travis still reports one test failure in other. Specifically in thealgorithms.other.detecting_english_programmatically, it tries to load a dictionary or something that doesn't exist

Raw log:
```
[1m    def loadDictionary():[0m
[1m        path = os.path.split(os.path.realpath(__file__))[0m
[1m        englishWords = {}[0m
[1m>       with open(path[0] + '/Dictionary.txt') as dictionaryFile:[0m
[1m[31mE       FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/slarse/Python/thealgorithms/other/Dictionary.txt'[0m
```

2019-02-22 13:32 UTC, martinnilsson93 commented on thealgorithms/other/anagrams.py
> +                    for word in word_list if len(anagram(word)) > 1}
Actually, now that I look for it, you added args for anagram but call them here as in the original code.

2019-02-23 12:11 UTC, mnil2 approved these changes

2019-02-23 12:11 UTC, martinnilsson93 commented
All good now :+1:

2019-02-23 12:11 UTC, larshum commented
That other problem was because the "snake_case all things" commit changed the filename of the `dictionary.txt` to lowercase, but forgot to update it to lowercase in `detecting_english_programmatically.py`. I missed that error locally because my file system is case-insensitive. :laughing:

2019-02-23 12:12 UTC, merged

2019-02-23 12:12 UTC, martinnilsson93 commented
I shouldve known it was the snake case guys fault all along